version: '3.8'

services:
    project.web:
        container_name: reportingportal-web-container
        image: reportingportalweb:latest 
        build: 
          context: .
          dockerfile: Dockerfile
        ports:
          - "3001:80"
        volumes:
          - .:/app
        networks:
          - reportingportal-net

networks:
  reportingportal-net:
    driver: bridge
